---
- hosts: 172.31.87.155
  become: yes
  tasks:
  - name: execute linux command
    command: hostname -f
    register: myfirsttskresult

  - name: i want to see first task result
    debug:
       msg:"{{myfirsttskresult}}"