---
- hosts: 172.31.87.155
  become: yes
  tasks:
  - include_tasks: myfile.yml

  - name: i want to copy file from ansible master to nodes
    copy:
       src: mystatic
       dest: /home/ubuntu/mystaticfile

  - name: i want to install webserver
    apt:
      name: apache2
      state: present  

  - name: copy dynamic file into node side
    template:
      src: myindexfile.j2
      dest: /var/www/html/index.html  

  - name: download remote file
    get_url:
       url: https://pixabay.com/photos/tree-sunset-clouds-sky-silhouette-736885/
       dest: /home/ubuntu/mystaticfile
       force_basic_auth: yes  
  handlers:
  - name: restartwebserver
    systemd:
       name: apache2
       state: restarted              
 
  